### ISSUE TITLE
--screenshot flag still broken

### ISSUE THREAD

**Issue by NotAShelf** [jirutka/swaylock-effects#11] opened 2022-09-05 08:49 UTC
I have recently came across your comment on [this issue](https://github.com/mortie/swaylock-effects/issues/85) in which you have announced it was fixed in version 1.6.10. However, I am experiencing this exact issue on a freshly built version of `swaylock-effects-git` (AUR) with package version `r402.9ac172a-1`

The issue is simply that  1/3 of the screen will be blank when `--screenshot` is passed and the screenshot will be fit inside the remaining 2/3, which is counterintuitive.

**Comment by NotAShelf** [comment] 2022-09-05 08:51
Output of `swaylock -v` as a followup:
```swaylock version v1.6.10-1-g4b54b85 (Sep  5 2022, branch 'master')```

**Comment by YHNdnzj** [comment] 2022-09-08 17:28
Running into this too on `sway-git`

**Comment by NotAShelf** [comment] 2022-09-08 19:23
@YHNdnzj could you confirm for me whether or not you're on a NVIDIA GPU?

I believe we have narrowed the issue down to my NVIDIA GPU or rather, the lack of proper screen capture support on it.

**Comment by YHNdnzj** [comment] 2022-09-09 04:08
@NotAShelf I'm using a laptop with NVIDIA Optimus, but manually specified `WLR_DRM_DEVICES` to make sway run on amdgpu.

**Comment by NotAShelf** [comment] 2022-09-11 17:27
It could possibly be something else, yes. I am unable to reproduce the broken --screenshot behaviour on an AMD gpu.

**Comment by vfosterm** [comment] 2022-10-07 14:15
Seems to be an nvidia gpu issue I have the exact same issues on my side.

**Comment by xi-pinmping** [comment] 2022-10-08 18:05
Having this issue on an AMD Radeon HD 6320 as well

**Comment by Haze-sh** [comment] 2022-10-21 10:33
I can reproduce this on a NIVIDIA GPU with wlroots-git AUR package. Sometimes it turns red screen and others white background but I can move the cursor though.

**Comment by Zeioth** [comment] 2022-11-27 20:14
Having the issue on AMD 6700XT too. Every other parameter apart from --screenshot seems to work fine.

**Comment by vfosterm** [comment] 2022-12-25 15:21
For those using hyprland the hyprland-nvidia-git package on AUR resolves the issue for me.
https://aur.archlinux.org/cgit/aur.git/tree/nvidia.patch?h=hyprland-nvidia-git

**Comment by Martinits** [comment] 2023-01-06 11:39
Have this issue on Intel i5-1260p, too. Using sway-effects-git (swaylock version v1.6.10-4-ga1cf657 (Jan  6 2023, branch 'master')) and sway(1.8) from archlinux. Get logs:
```
[ WARN:0@0.049] global /build/opencv/src/opencv-4.6.0/modules/videoio/src/cap_gstreamer.cpp (2401) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module source reported: Could not read from resource.
[ WARN:0@0.049] global /build/opencv/src/opencv-4.6.0/modules/videoio/src/cap_gstreamer.cpp (1356) open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0@0.049] global /build/opencv/src/opencv-4.6.0/modules/videoio/src/cap_gstreamer.cpp (862) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
```

**Comment by yannfill** [comment] 2023-01-06 17:22
Same issue as @Martinits with Intel GPU on Arch and Sway 1.8. Worked in Sway 1.7.

Could it be related to this new feature?

```
More robust and secure screen lockers via the new ext-session-lock-v1 protocol (supported by swaylock)
```

**Comment by lucaslira95** [comment] 2023-01-06 22:16
Same issue here too... (Sway 1.8, Swaylock Effects v1.6.10-4-ga1cf657)

**Comment by yannfill** [comment] 2023-01-12 23:43
Seems fixed with latest commit/merge.

**Comment by lucaslira95** [comment] 2023-01-13 00:42
After the last commit, the screen blink, then after one second the blur screen appears...

**Comment by Haze-sh** [comment] 2023-01-13 05:07
I can confirm it works now.

**Comment by jirutka** [comment] 2023-01-19 21:50
Thanks for the confirmation!

**Closed by jirutka** 2023-01-19 21:50 UTC
